services:
  sql:
    build:
      context: database
      dockerfile: Dockerfile
    command: --lower_case_table_names=1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
